#!/bin/bash
#
### BEGIN INIT INFO
# Provides:          rocket
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: noderocket rocket service
# Description:       noderocket rocket service
### END INIT INFO


# Source function library.
. /lib/lsb/init-functions


pidFile=/var/run/forever-initd-rocket.pid

ROCKET_HOME=/home/pi/noderocket-rocket
logFile=rocket.log
scriptId=server.js


start() {
    echo "Starting rocket server"

    # This is found in the library referenced at the top of the script
    start_daemon

    # Start our our rocket server through forever
    cd $ROCKET_HOME
    PATH=/usr/local/bin:$PATH
    echo "[`date -u +%Y-%m-%dT%T.%3NZ`] (sys) Starting" >> rocket.log
    NODE_ENV=production PORT=80 forever start --pidFile $pidFile -l $logFile -o $logFile -e $logFile -a -d $scriptId

    RETVAL=$?
}

restart() {
    echo -n "Restarting $scriptId"
    /usr/local/bin/forever restart $scriptId
    RETVAL=$?
}

stop() {
    echo -n "Shutting down $scriptId"
    /usr/local/bin/forever stop $scriptId
    RETVAL=$?
}

status() {
    echo -n "Status $scriptId"
    /usr/local/bin/forever list
    RETVAL=$?
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
